[package]
name = "audio_streaming"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15"
rustfft = "6.0"
egui = "0.22"
eframe = "0.22"
chrono = "0.4"
num-traits = "0.2"
anyhow = "1.0.70"
epi = "0.17"
jack = "0.5"
