[package]
name = "audio_streaming"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15"
rustfft = "6.0"
egui = "0.22"
eframe = "0.22"
chrono = "0.4"
num-traits = "0.2"
anyhow = "1.0.70"
epi = "0.17"
jack = "0.13.0"
log = "0.4"
env_logger = "0.10"
nom = "7.1.3"
memchr = "2.5.0"
rfd = "0.9"

[patch.crates-io]
jack = { git = "https://github.com/RustAudio/rust-jack.git", branch = "main" }

[package.metadata.rust-version]
version = "1.65.0"

[package.metadata.docs.rs]
all-features = true

[workspace.metadata.resolver]
version = "2"

[workspace.dependencies]
bitflags = "1.3.2"
